spring.application.name=rubrica

# Configurazione del database flessibile con variabili d'ambiente
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:rubrica_db}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# Configurazione del framework
server.forward-headers-strategy=framework

# Profilo di default attivo (Sviluppo)
spring.profiles.active=dev


# 1. Configurazione per il profilo SVILUPPO (dev)
%dev.logging.level.root=TRACE
%dev.spring.jpa.show-sql=true
%dev.spring.jpa.properties.hibernate.format_sql=true

# 2. Configurazione per il profilo PRODUZIONE (prod)
%prod.logging.level.root=INFO
%prod.spring.jpa.show-sql=false

# Espone gli endpoint necessari (in particolare /actuator/prometheus)
management.endpoints.web.exposure.include=health,info,prometheus
# Mostra dettagli completi sullo stato di salute della JVM
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}